//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Condition.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace dittlassian.Utilities.ConditionParser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ConditionLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		STRING=1, AND=2, OR=3, NOT=4, TRUE=5, FALSE=6, GT=7, GE=8, LT=9, LE=10, 
		EQ=11, NEQ=12, LPAREN=13, RPAREN=14, DECIMAL=15, IDENTIFIER=16, WS=17;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"STRING", "AND", "OR", "NOT", "TRUE", "FALSE", "GT", "GE", "LT", "LE", 
		"EQ", "NEQ", "LPAREN", "RPAREN", "DECIMAL", "IDENTIFIER", "WS"
	};


	public ConditionLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ConditionLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, "'&&'", "'||'", "'!'", "'true'", "'false'", "'>'", "'>='", 
		"'<'", "'<='", "'=='", "'!='", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "STRING", "AND", "OR", "NOT", "TRUE", "FALSE", "GT", "GE", "LT", 
		"LE", "EQ", "NEQ", "LPAREN", "RPAREN", "DECIMAL", "IDENTIFIER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Condition.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ConditionLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x13', 's', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x3', '\x2', '\x3', 
		'\x2', '\a', '\x2', '(', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '+', 
		'\v', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x5', '\x10', 'W', '\n', '\x10', '\x3', '\x10', '\x6', '\x10', 'Z', '\n', 
		'\x10', '\r', '\x10', '\xE', '\x10', '[', '\x3', '\x10', '\x3', '\x10', 
		'\x6', '\x10', '`', '\n', '\x10', '\r', '\x10', '\xE', '\x10', '\x61', 
		'\x5', '\x10', '\x64', '\n', '\x10', '\x3', '\x11', '\x3', '\x11', '\a', 
		'\x11', 'h', '\n', '\x11', '\f', '\x11', '\xE', '\x11', 'k', '\v', '\x11', 
		'\x3', '\x12', '\x6', '\x12', 'n', '\n', '\x12', '\r', '\x12', '\xE', 
		'\x12', 'o', '\x3', '\x12', '\x3', '\x12', '\x2', '\x2', '\x13', '\x3', 
		'\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', 
		'\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '\x3', '\x2', '\a', '\x5', '\x2', '\f', '\f', '\xF', '\xF', '$', 
		'$', '\x3', '\x2', '\x32', ';', '\x6', '\x2', '\x30', '\x30', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\a', '\x2', '\x30', '\x30', '\x32', 
		';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x5', '\x2', '\v', '\f', 
		'\xE', '\xF', '\"', '\"', '\x2', 'y', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '%', '\x3', '\x2', '\x2', '\x2', '\x5', '.', 
		'\x3', '\x2', '\x2', '\x2', '\a', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\t', '\x34', '\x3', '\x2', '\x2', '\x2', '\v', '\x36', '\x3', '\x2', 
		'\x2', '\x2', '\r', ';', '\x3', '\x2', '\x2', '\x2', '\xF', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\x11', '\x43', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'\x46', '\x3', '\x2', '\x2', '\x2', '\x15', 'H', '\x3', '\x2', '\x2', 
		'\x2', '\x17', 'K', '\x3', '\x2', '\x2', '\x2', '\x19', 'N', '\x3', '\x2', 
		'\x2', '\x2', '\x1B', 'Q', '\x3', '\x2', '\x2', '\x2', '\x1D', 'S', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', 'V', '\x3', '\x2', '\x2', '\x2', '!', '\x65', 
		'\x3', '\x2', '\x2', '\x2', '#', 'm', '\x3', '\x2', '\x2', '\x2', '%', 
		')', '\a', ')', '\x2', '\x2', '&', '(', '\n', '\x2', '\x2', '\x2', '\'', 
		'&', '\x3', '\x2', '\x2', '\x2', '(', '+', '\x3', '\x2', '\x2', '\x2', 
		')', '\'', '\x3', '\x2', '\x2', '\x2', ')', '*', '\x3', '\x2', '\x2', 
		'\x2', '*', ',', '\x3', '\x2', '\x2', '\x2', '+', ')', '\x3', '\x2', '\x2', 
		'\x2', ',', '-', '\a', ')', '\x2', '\x2', '-', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '.', '/', '\a', '(', '\x2', '\x2', '/', '\x30', '\a', '(', '\x2', 
		'\x2', '\x30', '\x6', '\x3', '\x2', '\x2', '\x2', '\x31', '\x32', '\a', 
		'~', '\x2', '\x2', '\x32', '\x33', '\a', '~', '\x2', '\x2', '\x33', '\b', 
		'\x3', '\x2', '\x2', '\x2', '\x34', '\x35', '\a', '#', '\x2', '\x2', '\x35', 
		'\n', '\x3', '\x2', '\x2', '\x2', '\x36', '\x37', '\a', 'v', '\x2', '\x2', 
		'\x37', '\x38', '\a', 't', '\x2', '\x2', '\x38', '\x39', '\a', 'w', '\x2', 
		'\x2', '\x39', ':', '\a', 'g', '\x2', '\x2', ':', '\f', '\x3', '\x2', 
		'\x2', '\x2', ';', '<', '\a', 'h', '\x2', '\x2', '<', '=', '\a', '\x63', 
		'\x2', '\x2', '=', '>', '\a', 'n', '\x2', '\x2', '>', '?', '\a', 'u', 
		'\x2', '\x2', '?', '@', '\a', 'g', '\x2', '\x2', '@', '\xE', '\x3', '\x2', 
		'\x2', '\x2', '\x41', '\x42', '\a', '@', '\x2', '\x2', '\x42', '\x10', 
		'\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\a', '@', '\x2', '\x2', '\x44', 
		'\x45', '\a', '?', '\x2', '\x2', '\x45', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\x46', 'G', '\a', '>', '\x2', '\x2', 'G', '\x14', '\x3', '\x2', 
		'\x2', '\x2', 'H', 'I', '\a', '>', '\x2', '\x2', 'I', 'J', '\a', '?', 
		'\x2', '\x2', 'J', '\x16', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\a', 
		'?', '\x2', '\x2', 'L', 'M', '\a', '?', '\x2', '\x2', 'M', '\x18', '\x3', 
		'\x2', '\x2', '\x2', 'N', 'O', '\a', '#', '\x2', '\x2', 'O', 'P', '\a', 
		'?', '\x2', '\x2', 'P', '\x1A', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', 
		'\a', '*', '\x2', '\x2', 'R', '\x1C', '\x3', '\x2', '\x2', '\x2', 'S', 
		'T', '\a', '+', '\x2', '\x2', 'T', '\x1E', '\x3', '\x2', '\x2', '\x2', 
		'U', 'W', '\a', '/', '\x2', '\x2', 'V', 'U', '\x3', '\x2', '\x2', '\x2', 
		'V', 'W', '\x3', '\x2', '\x2', '\x2', 'W', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'X', 'Z', '\t', '\x3', '\x2', '\x2', 'Y', 'X', '\x3', '\x2', '\x2', '\x2', 
		'Z', '[', '\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', '\x63', '\x3', '\x2', '\x2', 
		'\x2', ']', '_', '\a', '\x30', '\x2', '\x2', '^', '`', '\t', '\x3', '\x2', 
		'\x2', '_', '^', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\x3', '\x2', 
		'\x2', '\x2', '\x61', '_', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', 
		'\x3', '\x2', '\x2', '\x2', '\x62', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'\x63', ']', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\x3', '\x2', 
		'\x2', '\x2', '\x64', ' ', '\x3', '\x2', '\x2', '\x2', '\x65', 'i', '\t', 
		'\x4', '\x2', '\x2', '\x66', 'h', '\t', '\x5', '\x2', '\x2', 'g', '\x66', 
		'\x3', '\x2', '\x2', '\x2', 'h', 'k', '\x3', '\x2', '\x2', '\x2', 'i', 
		'g', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\x3', '\x2', '\x2', '\x2', 
		'j', '\"', '\x3', '\x2', '\x2', '\x2', 'k', 'i', '\x3', '\x2', '\x2', 
		'\x2', 'l', 'n', '\t', '\x6', '\x2', '\x2', 'm', 'l', '\x3', '\x2', '\x2', 
		'\x2', 'n', 'o', '\x3', '\x2', '\x2', '\x2', 'o', 'm', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'p', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\b', '\x12', '\x2', '\x2', 'r', '$', '\x3', '\x2', '\x2', 
		'\x2', '\n', '\x2', ')', 'V', '[', '\x61', '\x63', 'i', 'o', '\x3', '\b', 
		'\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace dittlassian.Utilities.ConditionParser
